#!/usr/bin/env python3
"""Compare benign lifecycle traces across raw provider pilots."""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from lssa.schema.events import EventType, StreamEvent
from scripts.summarize_real_pilot import (
    DEFAULT_ARTIFACTS_DIR,
    PilotTraceRow,
    collect_latest_trace_rows,
)

DEFAULT_PROVIDERS = (
    "openai_responses",
    "anthropic_messages",
    "aws_bedrock_converse",
)
DEFAULT_OUTPUT = Path("docs/pilot_runs/benign_lifecycle_comparison.md")
MODE_ORDER = {"streaming": 0, "nonstreaming": 1}


@dataclass(frozen=True)
class TraceObservation:
    row: PilotTraceRow
    event_types: tuple[str, ...]
    raw_event_types: tuple[str, ...]
    first_byte_raw_event: str
    first_token_raw_event: str
    chunk_raw_events: tuple[str, ...]
    stream_end_raw_event: str
    has_stream_lifecycle_order: bool
    has_nonstream_lifecycle_order: bool


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--providers",
        nargs="+",
        default=list(DEFAULT_PROVIDERS),
        help="providers to compare",
    )
    parser.add_argument("--artifacts-dir", type=Path, default=DEFAULT_ARTIFACTS_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if report is stale")
    args = parser.parse_args(argv)

    try:
        observations = collect_observations(args.artifacts_dir, tuple(args.providers))
        report = render_markdown(observations, args.artifacts_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != report:
            print(
                f"{args.output} is stale; run python scripts/compare_benign_lifecycle.py"
            )
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def collect_observations(
    artifacts_dir: Path,
    providers: tuple[str, ...],
) -> list[TraceObservation]:
    observations: list[TraceObservation] = []
    for provider in providers:
        rows = collect_latest_trace_rows(artifacts_dir, provider)
        for row in rows:
            events = _load_events(row.trace_path)
            if any(event.content is not None for event in events):
                raise ValueError(f"trace contains unredacted content fields: {row.trace_path}")
            observations.append(_observation_from_events(row, events))
    return sorted(
        observations,
        key=lambda item: (
            item.row.provider,
            item.row.prompt_id,
            MODE_ORDER.get(item.row.mode, 99),
            item.row.mode,
        ),
    )


def render_markdown(
    observations: list[TraceObservation],
    artifacts_dir: Path,
) -> str:
    if not observations:
        raise ValueError("cannot render an empty lifecycle comparison")

    provider_names = sorted({item.row.provider for item in observations})
    all_valid = all(item.row.valid for item in observations)
    all_redacted = all(item.row.unredacted_content_events == 0 for item in observations)

    lines = [
        "# Benign Lifecycle Comparison",
        "",
        "This report compares the latest redacted benign raw-provider traces across",
        f"`{artifacts_dir}`. It is generated by",
        "`python scripts/compare_benign_lifecycle.py`.",
        "",
        "## Status",
        "",
        "- Phase: P2.M4 benign lifecycle comparison",
        f"- Providers: {', '.join(f'`{provider}`' for provider in provider_names)}",
        f"- Latest traces compared: `{len(observations)}`",
        f"- Trace validity: `{_yes_no(all_valid)}`",
        f"- Content fields redacted: `{_yes_no(all_redacted)}`",
        "- Provider API calls in this report: historical local artifacts only; this",
        "  script does not call provider APIs.",
        "",
        "## Scope Boundary",
        "",
        "These are benign harness-validation traces. They do not measure safety",
        "policy strength, refusal rates, unsafe-content exposure, or guardrail",
        "behavior.",
        "",
        "## Provider Lifecycle Summary",
        "",
        "| Provider | Mode | Traces | Models | Valid | Mean TTFB ms | Mean TTFT ms | Terminal reasons | Lifecycle separability |",
        "| --- | --- | ---: | --- | ---: | ---: | ---: | --- | --- |",
    ]
    for summary in _provider_mode_summaries(observations):
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{summary['provider']}`",
                    f"`{summary['mode']}`",
                    str(summary["trace_count"]),
                    summary["models"],
                    _yes_no(bool(summary["valid"])),
                    _format_optional_float(summary["mean_ttfb_ms"]),
                    _format_optional_float(summary["mean_ttft_ms"]),
                    summary["terminal_reasons"],
                    summary["lifecycle_separability"],
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Event Mapping Surface",
            "",
            "| Provider | Mode | First byte raw event | First token raw event | Chunk raw events | Stream terminal raw event | Normalized events observed |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for surface in _event_mapping_surfaces(observations):
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{surface['provider']}`",
                    f"`{surface['mode']}`",
                    surface["first_byte_raw_event"],
                    surface["first_token_raw_event"],
                    surface["chunk_raw_events"],
                    surface["stream_end_raw_event"],
                    surface["event_types"],
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Lifecycle Findings",
            "",
            "- All compared traces are valid under the current normalized event-order",
            "  validator.",
            "- Streaming traces from all three providers expose enough raw events to map",
            "  `first_byte`, `first_token`, `chunk`, `stream_end`, `final_response`,",
            "  `iterator_end`, and `settled` as distinct normalized lifecycle events.",
            "- Non-streaming traces do not have a provider stream boundary, so",
            "  `stream_end` is not applicable; they still separate `final_response`,",
            "  `iterator_end`, and `settled` in the harness.",
            "- Terminal reasons are influenced by the conservative",
            "  `max_output_tokens=128` pilot limit. `length` here is a harness-limit",
            "  observation, not a provider safety signal.",
            "",
            "## P3 Decision",
            "",
            "P2.M4 is sufficient to complete P3.M1 policy scaffolding: redacted",
            "safety-category policy, prompt governance, and safety-signal trace",
            "contracts. It is not sufficient to start P3.M2 safety-signal pilot",
            "runs. P3.M2 should remain blocked until prompt sourcing, category labels,",
            "review policy, and output-retention rules are reviewed.",
            "",
        ]
    )
    return "\n".join(lines)


def _provider_mode_summaries(
    observations: list[TraceObservation],
) -> list[dict[str, object]]:
    grouped: dict[tuple[str, str], list[TraceObservation]] = {}
    for item in observations:
        grouped.setdefault((item.row.provider, item.row.mode), []).append(item)

    summaries = []
    for (provider, mode), items in sorted(
        grouped.items(),
        key=lambda pair: (pair[0][0], MODE_ORDER.get(pair[0][1], 99), pair[0][1]),
    ):
        terminal_reasons = Counter(item.row.terminal_reason for item in items)
        mean_ttfb_ms = _mean(item.row.ttfb_ms for item in items)
        mean_ttft_ms = _mean(item.row.ttft_ms for item in items)
        if mode == "streaming":
            separable = all(item.has_stream_lifecycle_order for item in items)
            lifecycle = (
                "`stream_end` / `final_response` / `iterator_end` / `settled`"
                if separable
                else "not fully separable"
            )
        else:
            separable = all(item.has_nonstream_lifecycle_order for item in items)
            lifecycle = (
                "`final_response` / `iterator_end` / `settled`; `stream_end` n/a"
                if separable
                else "not fully separable"
            )
        summaries.append(
            {
                "provider": provider,
                "mode": mode,
                "trace_count": len(items),
                "models": ", ".join(
                    f"`{model}`" for model in sorted({item.row.model for item in items})
                ),
                "valid": all(item.row.valid for item in items),
                "mean_ttfb_ms": mean_ttfb_ms,
                "mean_ttft_ms": mean_ttft_ms,
                "terminal_reasons": ", ".join(
                    f"`{reason}`={count}"
                    for reason, count in sorted(terminal_reasons.items())
                ),
                "lifecycle_separability": lifecycle,
            }
        )
    return summaries


def _event_mapping_surfaces(
    observations: list[TraceObservation],
) -> list[dict[str, str]]:
    grouped: dict[tuple[str, str], list[TraceObservation]] = {}
    for item in observations:
        grouped.setdefault((item.row.provider, item.row.mode), []).append(item)

    surfaces = []
    for (provider, mode), items in sorted(
        grouped.items(),
        key=lambda pair: (pair[0][0], MODE_ORDER.get(pair[0][1], 99), pair[0][1]),
    ):
        surfaces.append(
            {
                "provider": provider,
                "mode": mode,
                "first_byte_raw_event": _format_code_set(
                    item.first_byte_raw_event for item in items
                ),
                "first_token_raw_event": _format_code_set(
                    item.first_token_raw_event for item in items
                    if item.first_token_raw_event != "n/a"
                )
                or "n/a",
                "chunk_raw_events": _format_code_set(
                    raw for item in items for raw in item.chunk_raw_events
                )
                or "n/a",
                "stream_end_raw_event": _format_code_set(
                    item.stream_end_raw_event for item in items
                    if item.stream_end_raw_event != "n/a"
                )
                or "n/a",
                "event_types": _format_code_set(
                    event_type for item in items for event_type in item.event_types
                ),
            }
        )
    return surfaces


def _observation_from_events(
    row: PilotTraceRow,
    events: list[StreamEvent],
) -> TraceObservation:
    first_by_type: dict[EventType, StreamEvent] = {}
    for event in events:
        first_by_type.setdefault(event.event_type, event)

    return TraceObservation(
        row=row,
        event_types=tuple(event.event_type.value for event in events),
        raw_event_types=tuple(_raw_event_type(event) for event in events),
        first_byte_raw_event=_raw_event_type_or_na(first_by_type, EventType.FIRST_BYTE),
        first_token_raw_event=_raw_event_type_or_na(first_by_type, EventType.FIRST_TOKEN),
        chunk_raw_events=tuple(
            sorted(
                {
                    _raw_event_type(event)
                    for event in events
                    if event.event_type == EventType.CHUNK
                }
            )
        ),
        stream_end_raw_event=_raw_event_type_or_na(first_by_type, EventType.STREAM_END),
        has_stream_lifecycle_order=_has_order(
            events,
            [
                EventType.STREAM_END,
                EventType.FINAL_RESPONSE,
                EventType.ITERATOR_END,
                EventType.SETTLED,
            ],
        ),
        has_nonstream_lifecycle_order=_has_order(
            events,
            [
                EventType.FINAL_RESPONSE,
                EventType.ITERATOR_END,
                EventType.SETTLED,
            ],
        ),
    )


def _load_events(path: Path) -> list[StreamEvent]:
    events = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            events.append(StreamEvent.from_dict(json.loads(line)))
    if not events:
        raise ValueError(f"trace has no events: {path}")
    return events


def _has_order(events: list[StreamEvent], event_types: list[EventType]) -> bool:
    first_indexes: dict[EventType, int] = {}
    for index, event in enumerate(events):
        first_indexes.setdefault(event.event_type, index)
    indexes = [first_indexes.get(event_type) for event_type in event_types]
    if any(index is None for index in indexes):
        return False
    return indexes == sorted(indexes)


def _raw_event_type_or_na(
    first_by_type: dict[EventType, StreamEvent],
    event_type: EventType,
) -> str:
    event = first_by_type.get(event_type)
    return "n/a" if event is None else _raw_event_type(event)


def _raw_event_type(event: StreamEvent) -> str:
    value = event.metadata.get("raw_event_type")
    return value if isinstance(value, str) and value else "unknown"


def _mean(values: object) -> float | None:
    numbers = [value for value in values if isinstance(value, int | float)]
    if not numbers:
        return None
    return statistics.fmean(numbers)


def _format_code_set(values: object) -> str:
    unique = sorted({value for value in values if isinstance(value, str) and value})
    return ", ".join(f"`{value}`" for value in unique)


def _format_optional_float(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.3f}"


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"


if __name__ == "__main__":
    sys.exit(main())
